#!/bin/sh
#
# Usage: git-set-upstream UPSTREAM_BRANCH
#
# Set upstream branch of current branch to UPSTREAM_BRANCH.
#
# Written by Miles Bader <miles@gnu.org>
#

test $# = 1 || { echo "Usage: git set-upstream UPSTREAM_BRANCH"; exit 1; }
upstream="$1"
 
branch=`git rev-parse --abbrev-ref HEAD`
test $? -eq 0 || exit $?

if test x"$branch" = xHEAD; then
  echo 1>&2 "git set-upstream: Not on any branch"
  exit 2
fi

case "$upstream" in
  */*)
    ;;
  *)
    upstream="$upstream/master";;
esac

if git rev-parse 2>/dev/null >/dev/null "$upstream"; then
  :
else
  echo 1>&2 "git set-upstream: $upstream: Invalid upstream branch"
  exit 3
fi

git branch --set-upstream "$branch" "$upstream"
